USE quanlyphongkham_final
GO

-------------------STORE-PROCEDURE----------------------------------------

--1. Bảng PHANQUYEN
--1.1 SP_INSERT_PHANQUYEN
CREATE PROC SP_INSERT_PHANQUYEN
@QUYEN INT,
@GHICHU NVARCHAR(250)
AS
BEGIN
	INSERT dbo.PHANQUYEN
	        ( QUYEN, GHICHU )
	VALUES  ( @QUYEN, -- QUYEN - int
	          @GHICHU  -- GHICHU - nvarchar(250)
	          )
END
GO



--2. BẢNG TAIKHOAN
--2.1 SPINSERT_TAIKHOAN
DROP PROC dbo.SP_INSERT_TAIKHOAN
GO
CREATE PROC SP_INSERT_TAIKHOAN
	@TENDANGNHAP VARCHAR(50),
	@MATKHAU VARCHAR(50),
	@TENHIENTHI NVARCHAR(50),
	@MAPHANQUYEN int,
	@TRANGTHAI BIT
AS
BEGIN
	INSERT dbo.TAIKHOAN 
	        ( TENDANGNHAP ,
	          MATKHAU ,
	          TENHIENTHI ,
	          MAPHANQUYEN ,
	          TRANGTHAI
	        )
	VALUES  ( @TENDANGNHAP , -- TENDANGNHAP - varchar(50)
	          @MATKHAU , -- MATKHAU - varchar(50)
	          @TENHIENTHI , -- TENHIENTHI - nvarchar(50)
	          @MAPHANQUYEN , -- MAPHANQUYEN - int
	          @TRANGTHAI  -- TRANGTHAI - bit
	        )
END
GO


--2.2 SP_LOGIN

Drop PROC SP_LOGIN
GO

CREATE PROC SP_LOGIN
	@TenDangNhap VARCHAR(50),
	@MatKhau VARCHAR(50)
AS
BEGIN
	--SELECT dbo.FN_Login(@TenDangNhap,@MatKhau)
	SELECT T.MATK, T.MANV,T.TENDANGNHAP,T.MATKHAU,T.TENHIENTHI, P.QUYEN AS 'MAPHANQUYEN' , T.TRANGTHAI
	FROM TAIKHOAN T JOIN PHANQUYEN P ON T.MAPHANQUYEN = P.MAPHANQUYEN 
	WHERE T.TENDANGNHAP = @TENDANGNHAP AND T.MATKHAU = @MatKhau AND T.TRANGTHAI = 1 
END
GO

EXECUTE dbo.SP_LOGIN @TenDangNhap = 'bacsi', -- varchar(50)
    @MatKhau = '1' -- varchar(50)

GO
SELECT * FROM dbo.TAIKHOAN 
GO






--Bảng 3 BENHNHAN


--3.1  SP_DanhSachBenhNhan
DROP  PROC SP_DanhSachBenhNhan
GO

CREATE  PROC SP_DanhSachBenhNhan
AS
BEGIN
	SELECT	*
	FROM dbo.BENHNHAN
END
GO

EXEC dbo.SP_DanhSachBenhNhan
GO




 
-- 3.2 SP_TimKiemBenhNhan
DROP PROC SP_TimKiemBenhNhan_fTIepNhanBenhNhan
GO

CREATE PROC SP_TimKiemBenhNhan_fTIepNhanBenhNhan
	@TruongDuLieu VARCHAR(20),
	@ThongTin NVARCHAR(250)
 AS
 BEGIN 

	IF @TruongDuLieu = 'HOTEN'  SELECT * FROM dbo.BENHNHAN WHERE  HOTEN LIKE '%'+@ThongTin+'%'; 
	IF @TruongDuLieu = 'MABN'  SELECT * FROM dbo.BENHNHAN WHERE  MABN LIKE '%'+@ThongTin+'%';
	IF @TruongDuLieu = 'SODT'  SELECT * FROM dbo.BENHNHAN WHERE  SODT LIKE '%'+@ThongTin+'%';
	IF @TruongDuLieu = 'SOCMND'  SELECT * FROM dbo.BENHNHAN WHERE  SOCMND LIKE '%'+@ThongTin+'%';
	IF @TruongDuLieu = '*' SELECT * FROM dbo.BENHNHAN;
 END
 GO



 



 --- sp them benh nhan

 DROP PROC SP_InsertBenhNhan
 GO
 
 CREATE PROC SP_InsertBenhNhan
	@HOTEN nvarchar(50),
	@GIOITINH  BIT,
	@NGAYSINH  DATE,
	@DANTOC  nvarchar(50),
	@SOCMND  nvarchar(20),
	@DIACHI  nvarchar(250),
	@SODT  varchar(20),
	@TIENSU  nvarchar(250)
 AS
 BEGIN
	INSERT INTO dbo.BENHNHAN
	        ( HOTEN ,
	          GIOITINH ,
	          NGAYSINH ,
	          DANTOC ,
	          SOCMND ,
	          DIACHI ,
	          SODT ,
	          TIENSU
	        )
	VALUES  ( @HOTEN ,  @GIOITINH ,  @NGAYSINH ,   @DANTOC , @SOCMND ,  @DIACHI , @SODT ,  @TIENSU )
 END
 GO
 


 -- SP_UPDATE_BENHNHAN
 DROP PROC SP_UpdateBenhNhan
 GO
 
CREATE PROC SP_UpdateBenhNhan
	@MABN INT,
	@HOTEN NVARCHAR(50),
	@GIOITINH BIT,
	@NGAYSINH DATE,
	@DANTOC NVARCHAR(50),
	@SOCMND NVARCHAR(20),
	@DIACHI NVARCHAR(250),
	@SODT VARCHAR(20),
	@TIENSU NVARCHAR(250)
AS
BEGIN
	UPDATE  dbo.BENHNHAN  SET   HOTEN = @HOTEN , GIOITINH = @GIOITINH, NGAYSINH = @NGAYSINH,  DANTOC = @DANTOC,
								SOCMND = @SOCMND, DIACHI = @DIACHI , SODT = @SODT , TIENSU = @TIENSU
	    
				WHERE MABN = @MABN
				
END
GO


 

 -- sp danhsach nhanvien
 DROP PROC SP_DanhSachNhanVien
 GO

 CREATE PROC SP_DanhSachNhanVien
 AS
 BEGIN
	SELECT * FROM dbo.NHANVIEN
 END
 GO
 

 

 --sp danh sach hinh thuc kham
  DROP PROC SP_DanhSachHinhThucKham
  GO
  
 CREATE PROC SP_DanhSachHinhThucKham
 AS
 BEGIN
	SELECT * FROM dbo.HINHTHUCKHAM
 END
 GO



DROP PROC SP_DanhSachKham_fKhamBenNhan 
GO

CREATE PROC SP_DanhSachKham_fKhamBenNhan
 @NgayKham DATE
AS
BEGIN
		SELECT	P.MAPHIEUKHAM,B.MABN,B.HOTEN,convert(varchar, P.NGAYKHAM, 103) AS NGAYKHAM,B.SOCMND,B.SODT, B.DANTOC, P.KETLUAN,convert(varchar, B.NGAYSINH, 103) AS NGAYSINH,		 
				B.GIOITINH, B.DIACHI,H.TENHINHTHUCKHAM, P.CHUANDOAN, N.HOTEN AS 'BACSI'
		FROM dbo.PHIEUKHAM P JOIN dbo.BENHNHAN B ON B.MABN = P.MABN JOIN dbo.NHANVIEN N ON N.MANV = P.MANV 
		JOIN dbo.HINHTHUCKHAM H ON H.MAHINHTHUCKHAM = P.MAHINHTHUCKHAM
		WHERE P.NGAYKHAM = @NgayKham AND P.HOANTHANH = 0
END 
GO


EXECUTE dbo.SP_DanhSachKham_fKhamBenNhan
 @NgayKham = '2017-11-30 ' -- date


-- code cho phần thêm phiếu khám, hủy phiếu khám, và cập nhật phiếu khám
DROP PROC InsertPhieuKham
GO

CREATE PROC InsertPhieuKham
		 @MABN  INT,
         @MANV  INT,
		 @NVTIEPNHAN INT,
         @CHUANDOAN  nvarchar(250),
         @MAHINHTHUCKHAM  INT
AS
BEGIN
	INSERT INTO dbo.PHIEUKHAM( MABN, MANV, NVTIEPNHAN, CHUANDOAN, MAHINHTHUCKHAM ,HOANTHANH)  
	VALUES  ( @MABN ,  @MANV ,  @NVTIEPNHAN, @CHUANDOAN , @MAHINHTHUCKHAM ,0 )
	
END
GO


-- LICH SỬ KHÁM
-- SP_LOADLICHSUKHAMBYID
DROP PROC SP_LoadLichSuTiepNhanByID 
GO

CREATE PROC SP_LoadLichSuTiepNhanByID
	@MANV INT
AS
BEGIN
	SELECT	P.MAPHIEUKHAM, B.MABN,B.HOTEN, convert(varchar, P.NGAYKHAM, 103) AS NGAYKHAM,B.SOCMND,B.SODT, B.DANTOC, P.KETLUAN,convert(varchar, B.NGAYSINH, 103) AS NGAYSINH,		 
				B.GIOITINH, B.DIACHI,H.TENHINHTHUCKHAM, P.CHUANDOAN, N.HOTEN AS 'BACSI'
		FROM dbo.PHIEUKHAM P JOIN dbo.BENHNHAN B ON B.MABN = P.MABN JOIN dbo.NHANVIEN N ON N.MANV = P.MANV 
		JOIN dbo.HINHTHUCKHAM H ON H.MAHINHTHUCKHAM = P.MAHINHTHUCKHAM
		WHERE P.NVTIEPNHAN = @MANV
END

GO
	


--SP TimKiemLichSuTiepNhan
DROP  PROC TimKiemLichSuTiepNhan
GO

CREATE PROC TimKiemLichSuTiepNhan
	@MaNV INT,
	@TruongDuLieu VARCHAR(20),
	@ThongTin NVARCHAR(250)
 AS
 BEGIN 
	IF @TruongDuLieu = 'HOTEN'  
		SELECT	P.MAPHIEUKHAM, B.MABN,B.HOTEN, convert(varchar, P.NGAYKHAM, 103) AS NGAYKHAM,B.SOCMND,B.SODT, B.DANTOC, P.KETLUAN,convert(varchar, B.NGAYSINH, 103) AS NGAYSINH,		 
				B.GIOITINH, B.DIACHI,H.TENHINHTHUCKHAM, P.CHUANDOAN, N.HOTEN AS 'BACSI'
		FROM dbo.PHIEUKHAM P JOIN dbo.BENHNHAN B ON B.MABN = P.MABN JOIN dbo.NHANVIEN N ON N.MANV = P.MANV 
		JOIN dbo.HINHTHUCKHAM H ON H.MAHINHTHUCKHAM = P.MAHINHTHUCKHAM
		WHERE P.NVTIEPNHAN = @MANV AND   B.HOTEN LIKE '%'+@ThongTin+'%'; 
	IF @TruongDuLieu = 'MABN'  
		SELECT	P.MAPHIEUKHAM, B.MABN,B.HOTEN, convert(varchar, P.NGAYKHAM, 103) AS NGAYKHAM,B.SOCMND,B.SODT, B.DANTOC, P.KETLUAN,convert(varchar, B.NGAYSINH, 103) AS NGAYSINH,		 
				B.GIOITINH, B.DIACHI,H.TENHINHTHUCKHAM, P.CHUANDOAN, N.HOTEN AS 'BACSI'
		FROM dbo.PHIEUKHAM P JOIN dbo.BENHNHAN B ON B.MABN = P.MABN JOIN dbo.NHANVIEN N ON N.MANV = P.MANV 
		JOIN dbo.HINHTHUCKHAM H ON H.MAHINHTHUCKHAM = P.MAHINHTHUCKHAM
		WHERE P.NVTIEPNHAN = @MANV AND   B.MABN LIKE '%'+@ThongTin+'%';
	IF @TruongDuLieu = 'SODT' 
		SELECT	P.MAPHIEUKHAM, B.MABN,B.HOTEN, convert(varchar, P.NGAYKHAM, 103) AS NGAYKHAM,B.SOCMND,B.SODT, B.DANTOC, P.KETLUAN,convert(varchar, B.NGAYSINH, 103) AS NGAYSINH,		 
				B.GIOITINH, B.DIACHI,H.TENHINHTHUCKHAM, P.CHUANDOAN, N.HOTEN AS 'BACSI'
		FROM dbo.PHIEUKHAM P JOIN dbo.BENHNHAN B ON B.MABN = P.MABN JOIN dbo.NHANVIEN N ON N.MANV = P.MANV 
		JOIN dbo.HINHTHUCKHAM H ON H.MAHINHTHUCKHAM = P.MAHINHTHUCKHAM
		WHERE P.NVTIEPNHAN = @MANV AND   B.SODT LIKE '%'+@ThongTin+'%';
		
	IF @TruongDuLieu = 'SOCMND'  
		SELECT	P.MAPHIEUKHAM, B.MABN,B.HOTEN, convert(varchar, P.NGAYKHAM, 103) AS NGAYKHAM,B.SOCMND,B.SODT, B.DANTOC, P.KETLUAN,convert(varchar, B.NGAYSINH, 103) AS NGAYSINH,		 
				B.GIOITINH, B.DIACHI,H.TENHINHTHUCKHAM, P.CHUANDOAN, N.HOTEN AS 'BACSI'
		FROM dbo.PHIEUKHAM P JOIN dbo.BENHNHAN B ON B.MABN = P.MABN JOIN dbo.NHANVIEN N ON N.MANV = P.MANV 
		JOIN dbo.HINHTHUCKHAM H ON H.MAHINHTHUCKHAM = P.MAHINHTHUCKHAM
		WHERE P.NVTIEPNHAN = @MANV AND   B.SOCMND LIKE '%'+@ThongTin+'%';
	IF @TruongDuLieu = 'NGAYKHAM'
		SELECT	P.MAPHIEUKHAM, B.MABN,B.HOTEN, convert(varchar, P.NGAYKHAM, 103) AS NGAYKHAM,B.SOCMND,B.SODT, B.DANTOC, P.KETLUAN,convert(varchar, B.NGAYSINH, 103) AS NGAYSINH,		 
				B.GIOITINH, B.DIACHI,H.TENHINHTHUCKHAM, P.CHUANDOAN, N.HOTEN AS 'BACSI'
		FROM dbo.PHIEUKHAM P JOIN dbo.BENHNHAN B ON B.MABN = P.MABN JOIN dbo.NHANVIEN N ON N.MANV = P.MANV 
		JOIN dbo.HINHTHUCKHAM H ON H.MAHINHTHUCKHAM = P.MAHINHTHUCKHAM
		WHERE P.NVTIEPNHAN = @MANV AND   P.NGAYKHAM LIKE '%'+@ThongTin+'%';
END
 GO


 SELECT * FROM dbo.TAIKHOAN
 GO
 